name: Maven Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.3'
    - run: mvn -B clean package -DskipTests
    - uses: actions/upload-artifact@master
      with:
        name: searchui-module
        path: module/target
